APP_LAWYER.WEB/ViewModels/NavbarCategoriesViewComponent.cs
using APP_LAWYER.BLL;
using APP_LAWYER.WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace APP_LAWYER.WEB.Views.ViewModels;

public class NavbarCategoriesViewComponent : ViewComponent
{
    private readonly UOW _uow;

    public NavbarCategoriesViewComponent(UOW uow)
    {
        _uow = uow;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var categories = await _uow.CategoriRepository.ListAllAsync();
        var viewModel = new NavbarCategoriesViewModel
        {
            Categories = categories
        };
        return View(viewModel);
    }
}

APP_LAWYER.WEB/Controllers/CategoryController.cs
using APP_LAWYER.BLL;
using APP_LAWYER.WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace APP_LAWYER.WEB.Controllers;

public class CategoryController : Controller
{
    private readonly UOW _uow;

    public CategoryController(UOW uow)
    {
        _uow = uow;
    }

    // public async Task<IActionResult> Details(Guid id)
    // {
    //     var category = await _uow.CategoriRepository.GetByGuidAsync(id);
    //     var subcategories = await _uow.SubcategoryRepository.GetByCategoryIdAsync(id);
    //
    //     if (category == null) return NotFound();
    //
    //     var viewModel = new CategoryDetailsViewModel
    //     {
    //         Category = category,
    //         Subcategories = subcategories
    //     };
    //
    //     return View(viewModel);
    // }

    public async Task<IActionResult> Details(string slug)
    {
        var category = await _uow.CategoriRepository.GetBySlugAsyncRepo(slug);
        if (category == null) return NotFound();
        var subcategories = await _uow.SubcategoryRepository.GetByCategoryIdAsync(category.Id);
        var viewModel = new CategoryDetailsViewModel
        {
            Category = category,
            Subcategories = subcategories
        };
        return View(viewModel);
    }
    public async Task<IActionResult> NavbarCategories()
    {
        var categories = await _uow.CategoriRepository.ListAllAsync();
        var viewModel = new NavbarCategoriesViewModel
        {
            Categories = categories
        };
        return PartialView("_CategoriesPartial", viewModel);
    }
}

APP_LAWYER.WEB/Controllers/UserController.cs
using System.Security.Claims;
using APP_LAWYER.BLL;
using APP_LAWYER.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace APP_LAWYER.WEB.Controllers;

[Authorize]
public class UserController : Controller
{
    private readonly UOW _uow;

    public UserController(UOW uow)
    {
        _uow = uow;
    }

    public async Task<IActionResult> Index()
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
        if (userIdClaim == null) return BadRequest("User claim not found.");
        var userId = Guid.Parse(userIdClaim.Value);
        var documents = await _uow.DocumentRepository.ListAllAsync();
        var userDocuments = documents.Where(d => d.UserId == userId);
        return View(userDocuments);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var documentTemplates =
            await _uow.DocumentTemplateRepository
                .ListAllAsync(); // Измените на ваш метод для получения всех шаблонов документов
        return View(documentTemplates);
    }

    private async Task<string> GenerateContentAsync(Guid templateId, Guid userId)
    {
        var user = await _uow.UserRepository.GetByGuidAsync(userId);
        var template = await _uow.DocumentTemplateRepository.GetByGuidAsync(templateId);

        if (user == null || template == null) return null;
        var content = $"{template.Title}\n\n{template.Description}";
        return content;
    }

    [HttpPost]
    public async Task<IActionResult> CreateDocumentForUser(Guid templateId, string documentContent)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
        Console.WriteLine($"User ID Claim: {userIdClaim}");
        if (userIdClaim == null) return BadRequest("User claim not found.");
        var userId = Guid.Parse(userIdClaim.Value);
        Console.WriteLine($"User ID: {userId}");

        var user = await _uow.UserRepository.GetByGuidAsync(userId);
        if (user == null) return NotFound();

        var documentTemplate = await _uow.DocumentTemplateRepository.GetByGuidAsync(templateId);
        if (documentTemplate == null) return NotFound();
        var generatedDocumentContent = await GenerateContentAsync(templateId, userId);
        if (generatedDocumentContent == null) return BadRequest("Could not generate document content.");
        var document = new DocumentEntity
        {
            UserId = userId,
            Name = documentTemplate.Title,
            Description = documentContent
            // Fill in other fields as necessary...
        };
        // Insert the new document into the DocumentEntityRepository
        await _uow.DocumentRepository.InsertAsync(document);

        // Save changes to the database
        // await _uow.SaveChangesAsync();

        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Update(Guid id)
    {
        var document = await _uow.DocumentRepository.GetByGuidAsync(id);
        if (document == null) return NotFound();
        return View(document);
    }

    [HttpPost]
    public async Task<IActionResult> Update(DocumentEntity document)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
        if (userIdClaim == null)
        {
            Console.WriteLine("User claim not found Test Radik.", ClaimTypes.NameIdentifier);
            return BadRequest("User claim not found.");
        }

        var userId = Guid.Parse(userIdClaim.Value);

        // Получить существующий документ из базы данных
        var existingDocument = await _uow.DocumentRepository.GetByGuidAsync(document.Id);
        if (existingDocument == null) return NotFound();

        // Обновите поля существующего документа
        existingDocument.Name = document.Name;
        existingDocument.Description = document.Description;
        // Обновите другие поля по мере необходимости...

        if (!ModelState.IsValid)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            foreach (var error in errors) Console.WriteLine("TEST TORE", error.ErrorMessage);
            return View(document);
        }

        // Сохраните обновленный документ
        await _uow.DocumentRepository.UpdateAsync(existingDocument);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(Guid id)
    {
        var document = await _uow.DocumentRepository.GetByGuidAsync(id);
        if (document != null) await _uow.DocumentRepository.DeleteAsync(document);
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> EditProfile()
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
        if (userIdClaim == null) return BadRequest("User claim not found.");
        var userId = Guid.Parse(userIdClaim.Value);
        var user = await _uow.UserRepository.GetByGuidAsync(userId);
        if (user == null) return NotFound();
        return View(user);
    }

    [HttpPost]
    public async Task<IActionResult> EditProfile(User model)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
        if (userIdClaim == null) return BadRequest("User claim not found.");
        var userId = Guid.Parse(userIdClaim.Value);
        var user = await _uow.UserRepository.GetByGuidAsync(userId);
        if (user == null) return NotFound();
        user.FirstName = model.FirstName;
        user.LastName = model.LastName;
        user.Email = model.Email;
        await _uow.UserRepository.UpdateAsync(user);
        return RedirectToAction("Index");
    }
}

APP_LAWYER.WEB/Views/Shared/_CategoriesPartial.cshtml
@model NavbarCategoriesViewModel

@foreach (var category in Model.Categories)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Category" asp-action="Details" asp-route-id="@category.Id">@category.Name</a>
    </li>
}

APP_LAWYER.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PRIME LEGAL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/APP_LAWYER.WEB.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    @RenderSection("MetaTags", false)
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Z8N8VLS8PL"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-Z8N8VLS8PL');
    </script>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-T7JC2G6');</script>
    <!-- End Google Tag Manager -->
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
       (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
       m[i].l=1*new Date();
       for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
       k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
       (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
    
       ym(94231347, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true
       });
    </script>
    <noscript>
        <div>
            <img src="https://mc.yandex.ru/watch/94231347" style="position:absolute; left:-9999px;" alt=""/>
        </div>
    </noscript>
    <!-- /Yandex.Metrika counter -->
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T7JC2G6"
            height="0" width="0" style="display:none;visibility:hidden">
    </iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PRIME LEGAL</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    @await Component.InvokeAsync("NavbarCategories")
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Мои документы</a> *@
                            <a href="@Url.Action("Index", "User")" class="nav-link text-dark">Мои документы</a>
                        </li>
                        <li class="nav-item">
                            <form asp-controller="Account" asp-action="Logout" method="post">
                                <button type="submit" class="nav-link text-dark btn btn-link">Выйти</button>
                            </form>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#loginModal" style="margin-right: 10px;">Войти</button>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Registration", "Account")" class="btn btn-primary">Зарегистрироваться</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Вход на сайт</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="Login" asp-controller="Account" asp-anti-forgery="true" style="max-width: 600px; margin: auto;">
                    <div class="validation" asp-validation-summary="ModelOnly"></div>
                    <div>
                        <div class="form-group">
                            <label for="LayoutPhoneNumber">Номер телефона</label>
                            <input type="tel" id="LayoutPhoneNumber" name="PhoneNumber" placeholder="8707777777" style="width: 100%; margin-bottom: 20px;"/>
                            <span class="field-validation-valid" data-valmsg-for="PhoneNumber" data-valmsg-replace="true"></span>
                        </div>
                        <div class="form-group">
                            <label for="LayoutPassword">Пароль</label>
                            <input type="password" id="LayoutPassword" name="Password" style="width: 100%; margin-bottom: 20px;"/>
                            <span class="field-validation-valid" data-valmsg-for="Password" data-valmsg-replace="true"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="ВОЙТИ" class="btn btn-warning" style="margin-top: 20px; border-radius: 3px;"/>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<a aria-label="Chat on WhatsApp" href="https://wa.me/77073816081?text=Здравствуйте,%20мне%20нужна%20юридическая%20помощь." class="whatsapp-button" style="z-index: 1000;">
    <img alt="Chat on WhatsApp" src="~/ChatOnWhatsAppButton/WhatsAppButtonGreenSmall.png"/>
</a>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year - PRIME LEGAL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        <a href="https://www.instagram.com/torekhan_mukhtarov/" target="_blank">
            <i class="fab fa-instagram"></i>
        </a>
        <a href="https://www.facebook.com/tore.mukha" target="_blank">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a href="https://twitter.com/your_username" target="_blank">
            <i class="fab fa-twitter"></i>
        </a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>