APP_LAWYER.WEB/Areas/Admin/Controllers/DocumentTemplateController.cs
using APP_LAWYER.BLL;
using APP_LAWYER.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace APP_LAWYER.WEB.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "1")]
public class DocumentTemplateController : Controller
{
    private readonly UOW _uow;

    public DocumentTemplateController(UOW uow)
    {
        _uow = uow;
    }

    public async Task<IActionResult> Index()
    {
        var templates = await _uow.DocumentTemplateRepository.ListAllAsync();
        return View(templates);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(DocumentTemplate documentTemplate)
    {
        if (!ModelState.IsValid)
        {
            var errors = ModelState.SelectMany(x => x.Value.Errors.Select(z => z.ErrorMessage));
            foreach (var error in errors)
            {
                Console.WriteLine(error);
            }
            return View(documentTemplate);
        }

        Console.WriteLine("Model is valid");
        await _uow.DocumentTemplateRepository.InsertAsync(documentTemplate);
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Update(Guid id)
    {
        Console.WriteLine("Searching for document template with id: " + id);
        var documentTemplate = await _uow.DocumentTemplateRepository.GetByGuidAsync(id);
        if (documentTemplate == null)
        {
            Console.WriteLine("Document template not found");
            return NotFound();
        }

        return View(documentTemplate);
    }

    [HttpPost]
    public async Task<IActionResult> Update(DocumentTemplate documentTemplate)
    {
        if (ModelState.IsValid)
        {
            await _uow.DocumentTemplateRepository.UpdateAsync(documentTemplate);
            return RedirectToAction(nameof(Index));
        }
        return View(documentTemplate);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(Guid id)
    {
        var documentTemplate = await _uow.DocumentTemplateRepository.GetByGuidAsync(id);
        if (documentTemplate == null) return NotFound();
        return View(documentTemplate);
    }

    [HttpPost]
    [ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        var documentTemplate = await _uow.DocumentTemplateRepository.GetByGuidAsync(id);
        await _uow.DocumentTemplateRepository.DeleteAsync(documentTemplate);
        return RedirectToAction(nameof(Index));
    }
}

APP_LAWYER.WEB/Areas/Admin/Views/DocumentTemplate/Create.cshtml
@model APP_LAWYER.DAL.Entities.DocumentTemplate

@{
    ViewBag.Title = "Create Document Template";
    Layout = "_Layout";
}

<h2>Create Document Template</h2>

<form asp-action="Create" method="post" class="mt-4">
    <div class="form-group">
        <label for="Title">Title</label>
        <input class="form-control" name="Title" id="Title" type="text" required>
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea id="Description" name="Description" class="form-control" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script src="https://cdn.ckeditor.com/4.16.0/full-all/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Description', {
       toolbar: 'Full',
    });
</script>
<script>
$(document).ready(function() {
    $('form').on('submit', function() {
        for (var instanceName in CKEDITOR.instances) {
            CKEDITOR.instances[instanceName].updateElement();
        }
    });
});
</script>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

APP_LAWYER.WEB/Areas/Admin/Views/DocumentTemplate/Delete.cshtml
@model APP_LAWYER.DAL.Entities.DocumentTemplate

@{
    ViewBag.Title = "Delete Document Template";
    Layout = "_Layout";
}

<h2>Delete Document Template</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DocumentTemplate</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed" method="post">
        <input type="hidden" asp-for="@Model.Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a href="@Url.Action("Index", "DocumentTemplate", new { id = Model.Id })">Back to Index</a>
    </form>
</div>

APP_LAWYER.WEB/Areas/Admin/Views/DocumentTemplate/Index.cshtml
@using APP_LAWYER.WEB.Areas.Admin.Models
@model IEnumerable<APP_LAWYER.DAL.Entities.DocumentTemplate>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>

<p>
    <a href="@Url.Action("Create", "DocumentTemplate")" class="btn btn-primary">Create New Template</a>
</p>

<table class="table">
    <thead>
    <tr>
        <th>Имя подкатегории</th>
        <th>Описание</th>
        <th>Действия</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var template in Model)
    {
        <tr>
            <td>@template.Title</td>
            <td>@Html.Raw(template.Description.TruncateAtWord(10))</td>
            <td>
                <div class="d-flex">
                    <a href="@Url.Action("Update", "DocumentTemplate", new { id = template.Id })" class="btn btn-primary mr-2">Редактировать</a>
                    <a href="@Url.Action("Delete", "DocumentTemplate", new { id = template.Id })" class="btn btn-danger">Удалить</a>
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>

APP_LAWYER.WEB/Areas/Admin/Views/DocumentTemplate/Update.cshtml
@model APP_LAWYER.DAL.Entities.DocumentTemplate

@{
    ViewBag.Title = "Update Document Template";
    Layout = "_Layout";
}

<h2>Update Document Template</h2>

<form asp-action="Update" method="post">
    <input type="hidden" asp-for="Id"/>

    <div class="form-group">
        <label for="Title">Title</label>
        <input id="Title" name="Title" class="form-control" value="@Model.Title"/>
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea id="Description" name="Description" class="form-control" rows="5">@Model.Description</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>
<script src="https://cdn.ckeditor.com/4.16.0/full-all/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Description', {
        toolbar: [
                { name: 'clipboard', items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
                { name: 'editing', items: [ 'Scayt' ] },
                { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
                { name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ] },
                { name: 'tools', items: [ 'Maximize' ] },
                { name: 'document', items: [ 'Source' ] },
                '/',
                { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Strike', '-', 'RemoveFormat' ] },
                { name: 'styles', items: [ 'Styles', 'Format' ] },
                { name: 'about', items: [ 'About' ] },
                { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] },
            ]
    });
</script>