APP_LAWYER.WEB/Models/HomeViewModel.cs
using APP_LAWYER.DAL.Entities;

namespace APP_LAWYER.WEB.Models;

public class HomeViewModel
{
    public IEnumerable<Subcategory> Subcategories { get; set; }
    public IEnumerable<Category> Categories { get; set; }
}

APP_LAWYER.WEB/Controllers/CategoryController.cs
using APP_LAWYER.BLL;
using APP_LAWYER.WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace APP_LAWYER.WEB.Controllers;

public class CategoryController : Controller
{
    private readonly UOW _uow;

    public CategoryController(UOW uow)
    {
        _uow = uow;
    }

    // public async Task<IActionResult> Details(Guid id)
    // {
    //     var category = await _uow.CategoriRepository.GetByGuidAsync(id);
    //     var subcategories = await _uow.SubcategoryRepository.GetByCategoryIdAsync(id);
    //
    //     if (category == null) return NotFound();
    //
    //     var viewModel = new CategoryDetailsViewModel
    //     {
    //         Category = category,
    //         Subcategories = subcategories
    //     };
    //
    //     return View(viewModel);
    // }

    public async Task<IActionResult> Details(string slug)
    {
        var category = await _uow.CategoriRepository.GetBySlugAsyncRepo(slug);
        if (category == null) return NotFound();
        var subcategories = await _uow.SubcategoryRepository.GetByCategoryIdAsync(category.Id);
        var viewModel = new CategoryDetailsViewModel
        {
            Category = category,
            Subcategories = subcategories
        };
        return View(viewModel);
    }
    public async Task<IActionResult> NavbarCategories()
    {
        var categories = await _uow.CategoriRepository.ListAllAsync();
        var viewModel = new NavbarCategoriesViewModel
        {
            Categories = categories
        };
        return PartialView("_CategoriesPartial", viewModel);
    }
}

APP_LAWYER.WEB/Controllers/HomeController.cs
using System.Diagnostics;
using APP_LAWYER.BLL;
using APP_LAWYER.WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace APP_LAWYER.WEB.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly UOW _uow;

    public HomeController(ILogger<HomeController> logger, UOW uow)
    {
        _logger = logger;
        _uow = uow;
    }


    public async Task<IActionResult> Index()
    {
        var subcategories = await _uow.SubcategoryRepository.ListAllAsync();
        var categories = await _uow.CategoriRepository.ListAllAsync();
        var model = new HomeViewModel
        {
            Categories = categories,
            Subcategories = subcategories
        };
        return View(model);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

APP_LAWYER.WEB/Controllers/SubcategoryController.cs
using System.Security.Claims;
using APP_LAWYER.BLL;
using APP_LAWYER.DAL.Entities;
using APP_LAWYER.DAL.Enums;
using Google.Apis.Services;
using Google.Apis.YouTube.v3;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace APP_LAWYER.WEB.Controllers;

// [Authorize]
public class SubcategoryController : Controller
{
    private readonly UOW _uow;

    public SubcategoryController(UOW uow)
    {
        _uow = uow;
    }

    [HttpGet]
    public async Task<IActionResult> ViewSubcategory(string slug)
    {
        var subcategory = await _uow.SubcategoryRepository.GetBySlugAsync(slug);

        if (subcategory == null)
        {
            return NotFound();
        }

        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // Получить ID текущего пользователя

        if (userId == null)
        {
            // Если пользователь не авторизован, перенаправить его на страницу входа
            return Challenge();
        }

        Guid guidUserId;
        if (!Guid.TryParse(userId, out guidUserId))
        {
            // Обработка ошибки, если userId не может быть преобразован в Guid
            return BadRequest("Invalid user ID");
        }

        var user = await _uow.UserRepository.Get(u => u.Id == guidUserId, include: u => u.Role);

        if (user == null)
        {
            // Если пользователь не найден в базе данных, показать ошибку
            return NotFound();
        }

        if (user.Role.RoleName != subcategory.Role.RoleName)
        {
            // Если пользователь не имеет необходимой роли, показать ему страницу с ошибкой 403
            return Forbid();
        }

        // Если все проверки пройдены, показать подкатегорию
        return View("DetailsForModerators", subcategory);
    }

    public async Task<IActionResult> Index(Guid id)
    {
        var subcategory = await _uow.SubcategoryRepository.GetByGuidAsync(id);
        subcategory.SubcategoryVideos = await _uow.SubcategoryVideoRepository
            .GetAll()
            .Include(sv => sv.Video)
            .Where(sv => sv.SubcategoryId == subcategory.Id)
            .ToListAsync();
        subcategory.SubcategoryVideos = subcategory.SubcategoryVideos.OrderBy(sv => sv.Video.Title).ToList();

        ViewBag.SubcategoryId = subcategory.Id;
        return View(subcategory);
    }

    [HttpGet]
    public async Task<IActionResult> Index(string slug)
    {
        var subcategory = await _uow.SubcategoryRepository.GetBySlugAsyncRepo(slug);
        if (subcategory == null) return NotFound();
    
        if (User.Identity.IsAuthenticated)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // Получить ID текущего пользователя

            Guid guidUserId;
            if (!Guid.TryParse(userId, out guidUserId))
            {
                // Обработка ошибки, если userId не может быть преобразован в Guid
                return BadRequest("Invalid user ID");
            }

            var user = await _uow.UserRepository.Get(u => u.Id == guidUserId, include: u => u.Role);

            if (user == null)
            {
                // Если пользователь не найден в базе данных, показать ошибку
                return NotFound();
            }

            if (user.Role.RoleName != RoleName.Moderator && user.Role.RoleName != RoleName.SuperAdmin)
            {
                // Если пользователь не имеет необходимой роли, показать ему страницу с ошибкой 403
                return Forbid();
            }
            
            subcategory.SubcategoryVideos = await _uow.SubcategoryVideoRepository
                .GetAll()
                .Include(sv => sv.Video)
                .Where(sv => sv.SubcategoryId == subcategory.Id)
                .ToListAsync();
            subcategory.SubcategoryVideos = subcategory.SubcategoryVideos.OrderBy(sv => sv.Video.Title).ToList();
        }

        ViewBag.SubcategoryId = subcategory.Id;
        return View(subcategory);
    }
    
    public async Task<IActionResult> Comments(Guid id)
    {
        var comments = await _uow.CommentRepository.GetBySubcategoryIdAsync(id);
        return PartialView("_Comments", comments);
    }

    public async Task<VideoInfo> GetVideoInfo(string videoId)
    {
        var youtubeService = new YouTubeService(new BaseClientService.Initializer
        {
            ApiKey = "AIzaSyC2r-I1RQi2TpyW9Ef7iRFRhI7b8t-c1PU", // Ваш API ключ
            ApplicationName = "prime-legal-385809" // Имя вашего приложения
        });

        var videoRequest = youtubeService.Videos.List("snippet, contentDetails");
        videoRequest.Id = videoId;

        var videoResponse = await videoRequest.ExecuteAsync();

        var videoInfo = new VideoInfo();
        foreach (var video in videoResponse.Items)
        {
            videoInfo.Title = video.Snippet.Title;
            videoInfo.Description = video.Snippet.Description;
            videoInfo.Duration = video.ContentDetails.Duration;
        }

        return videoInfo;
    }

    [HttpPost]
    [Route("/Subcategory/GetNextVideoId")]
    public async Task<string> GetNextVideoId(int index)
    {
        var videos = await _uow.SubcategoryVideoRepository
            .GetAll()
            .Include(sv => sv.Video)
            .OrderBy(sv => sv.Video.Title)
            .ToListAsync();
        if (index < 0 || index >= videos.Count) return null;
        var nextIndex = (index + 1) % videos.Count;
        return videos[nextIndex].Video.YoutubeId;
    }
}

APP_LAWYER.WEB/Views/Home/Index.cshtml
@model HomeViewModel

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
        @for (var i = 0; i < Model.Subcategories.Count(); i++)
        {
            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@i" class="@(i == 0 ? "active" : "")"></li>
        }
    </ol>
    <div class="carousel-inner">
        @for (var i = 0; i < Model.Subcategories.Count(); i++)
        {
            var item = Model.Subcategories.ElementAt(i);
            <div class="carousel-item @(i == 0 ? "active" : "")">
                <img src="@(!string.IsNullOrEmpty(item.ImagePath) ? item.ImagePath : item.Image)" class="d-block w-100" alt="@item.Description">
                <a href="@Url.Action("Index", "Subcategory", new { slug = item.Slug })">
                    <div class="carousel-caption d-none d-md-block" style="background-color: rgba(0, 0, 0, 0.5);">
                        <h5>@item.Name</h5>
                        <p>@Html.Raw(item.Description)</p>
                    </div>
                </a>
            </div>
        }
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </a>
</div>
<div class="row">
    @foreach (var category in Model.Categories)
    {
        <div class="col-sm-4">
            <div class="card shadow mt-4 bg-secondary bg-light">
                <div class="card-body card-content d-grid">
                    <h5 class="card-title text-muted">@category.Name</h5>
                    <p class="card-text text-muted">@category.Description</p>
                    <a href="@Url.Action("Details", "Category", new { slug = category.Slug })" class="btn btn-primary">Подробнее</a>
                    @* <a href="@Url.Action("Details", "Category", new { id = category.Id })" class="btn btn-primary">Подробнее</a> *@
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    <script>
        $(document).ready(function() {
            var maxHeight = 0;
            $(".card-content").each(function(){
                if ($(this).height() > maxHeight) { maxHeight = $(this).height(); }
            });
            $(".card-content").height(maxHeight);
        });
    </script>
}